apiVersion: v1
kind: ServiceAccount
metadata:
  name: predictive-scaler
  namespace: httpbin
  annotations:
    # CHANGE-ME: paste `terraform output predictive_scaler_role_arn` here.
    eks.amazonaws.com/role-arn: "arn:aws:iam::CHANGE-ME-ACCOUNT-ID:role/httpbin-dev-predictive-scaler-role"
automountServiceAccountToken: true
